# Generated by Django 5.0.1 on 2024-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_idea', '0002_alter_places_character_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=None, null=True, verbose_name='Цена'),
        ),
    ]
