# Generated by Django 5.0.1 on 2024-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_idea', '0004_alter_places_character_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='one_photo_place',
            field=models.ImageField(upload_to='photo_ideas/', verbose_name='Фото'),
        ),
    ]
